routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,

)

from models.user import User
from models.topic import Topic
from models.reply import Reply
import os
import uuid
from utils import log

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/settings', methods=['GET', 'POST'])
def settings():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('settings.html', user=u)


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        ts = sorted(User.topics(u), key=lambda x:x.ct, reverse=True)
        rs = sorted(User.replies(u), key=lambda x:x.ct, reverse=True)
        rts = []
        for r in rs:
            rts.append(r.topic())
        return render_template('profile.html', user=u, topics=ts, reply_titles=rts)


def valid_suffix(suffix):
    valid_type = ['jpg', 'png', 'jpeg']
    return suffix in valid_type


@main.route('/image/add', methods=["POST"])
def add_img():
    u = current_user()

    # file 是一个上传的文件对象
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        # 上传的文件一定要用 secure_filename 函数过滤一下名字
        # ../../../../../../../root/.ssh/authorized_keys
        # filename = secure_filename(file.filename)
        # 2017/6/14/19/56/yiasduifhy289389f.png
        # import time
        # filename = str(time.time()) + filename
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        User.update(u.id, dict(
            user_image='/uploads/' + filename
        ))

    return redirect(url_for(".profile"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory('user_image', filename)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic


main = Blueprint('topic', __name__)


@main.route("/")
def index():
    ms = Topic.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, u=u)


@main.route('/<int:id>')
def detail(id):
    # http://localhost:2000/topic/1
    m = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    return render_template("topic/new.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/'>首页</a></li>

        <li>
            <a href='/my/messages'>

              未读消息
            </a>
        </li>

        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8"/>
  <link rel="stylesheet" href="//o4j806krb.qnssl.com/public/stylesheets/index.min.bdd5dd43.min.css" media="all" />
  <title>{{user.username}} 的个人主页</title>
</head>
<body>

<div id='main'>

    <div id='sidebar'>

      <div class='panel'>

        <div class='header'>
          <span class='col_fade'>个人信息</span>
        </div>
        <div class='inner'>
          <div class='user_card'>
              <div>
                <a class='user_avatar' href="{{url_for('index.user_detail', id=user.id)}}">
                  <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120">
                </a>
                <span class='user_name'><a class='dark'>{{user.username}}</a></span>

                <div class="space clearfix"></div>
                <span class="signature">
                    “
                        没有签名
                    ”
                </span>
              </div>
          </div>
        </div>
      </div>
    </div>


<div id='content'>
  <div class='panel'>
    <div class='header'>
      <ul class='breadcrumb'>
        <li><a href='/'>主页</a><span class='divider'>/</span></li>
      </ul>
    </div>
    <div class='inner userinfo'>
      <div class='user_big_avatar'>
        <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120" class="user_avatar" title="i5ting"/>
      </div>
      <a class='dark'>{{user.username}}</a>


      <p class='col_fade'>注册时间 3 年前</p>
      
    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>最近创建的话题</span>
    </div>


    {% for t in topics %}
        <div class='cell'>

          <a class="user_avatar pull-left" href="/user/i5ting">
            <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120"
                 title="i5ting"
                    />
          </a>


          <a class='last_time pull-right' href="/topic/5a41e5e7d1536726354b8140#5a4488e7f320ae9f0dd5812d">
            <img class="user_small_avatar" src="https://avatars2.githubusercontent.com/u/20757983?v=4&amp;s=120">
            <span class="gua-time" data-ct="{{ t.ct }}"></span>
          </a>



          <div class="topic_title_wrapper">
              <span>{{ t.reply_count() }} / {{ t.views }}</span>

              <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                 {{ t.title }}
              </a>
          </div>
        </div>
    {% endfor %}

  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>最近参与的话题</span>
    </div>
    
    {% for rt in reply_titles %}
        <div class='cell'>

          <a class="user_avatar pull-left" href="/user/i5ting">
            <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120"
                 title="i5ting"
                    />
          </a>


          <a class='last_time pull-right' href="/topic/5a41e5e7d1536726354b8140#5a4488e7f320ae9f0dd5812d">
            <img class="user_small_avatar" src="https://avatars2.githubusercontent.com/u/20757983?v=4&amp;s=120">
            <span class="gua-time" data-ct="{{ rt.ct }}"></span>
          </a>



          <div class="topic_title_wrapper">
              <span>{{ rt.reply_count() }} / {{ rt.views }}</span>

              <a class="topic_title" href="{{ url_for('topic.detail', id=rt.id) }}">
                 {{ rt.title }}
              </a>
          </div>
        </div>
    {% endfor %}

  </div>
</div>



</div>



<script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            var code_list = es('pre code')
            for (var i = 0; i < code_list.length; i++) {
                var code = code_list[i]
                code.className = code.className.replace('lang', 'language')
            }
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.gua-time')
                for (var i = 0; i < times.length; i++) {
                    var t = times[i]
                    var time = Number(t.dataset.ct)
                    var now = Math.floor(new Date() / 1000)
                    var delta =  Math.floor((now - time)/60)
                    var s = `${delta} 分钟前`
                    t.innerText = s
                }
            }, 1000)
        }

        var __main = function () {
            markContents()
            registerTimer()
            highlight()
        }

        __main()
</script>



</body>
</html>

templates/settings.html
{% extends "topic/base.html" %}
{% block title %}
新建帖子
{% endblock %}
{% block main %}

<div id='main'>

    <div id='sidebar'>

      <div class='panel'>

        <div class='header'>
          <span class='col_fade'>个人信息</span>
        </div>
        <div class='inner'>
          <div class='user_card'>
              <div>
                <a class='user_avatar' href="{{url_for('index.user', id=user.id)}}">
                  <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120">
                </a>
                <span class='user_name'><a class='dark'>{{user.username}}</a></span>

                <div class="space clearfix"></div>
                <span class="signature">
                    “
                        没有签名
                    ”
                </span>
              </div>
          </div>
        </div>
      </div>
    </div>


<div id='content'>
  <div class='panel'>
    <div class='header'>
      <ul class='breadcrumb'>
        <li><a href='/'>主页</a><span class='divider'>/</span></li>
      </ul>
    </div>
    <div class='inner userinfo'>
      <div class='user_big_avatar'>
        <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120" class="user_avatar" title="i5ting"/>
      </div>
      <a class='dark'>{{user.username}}</a>


      <p class='col_fade'>注册时间 3 年前</p>

    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>设置</span>
    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>更改密码</span>
    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>上传头像</span>
      <form method=post
          action='{{ url_for(".add_img") }}'
          enctype=multipart/form-data>
        <input type=file name=avatar>
        <button type="submit">Upload</button>
      </form>
      <img src="{{ user.user_image }}" title="avatar"/>
    </div>
  </div>
</div>



</div>



<script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            var code_list = es('pre code')
            for (var i = 0; i < code_list.length; i++) {
                var code = code_list[i]
                code.className = code.className.replace('lang', 'language')
            }
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.gua-time')
                for (var i = 0; i < times.length; i++) {
                    var t = times[i]
                    var time = Number(t.dataset.ct)
                    var now = Math.floor(new Date() / 1000)
                    var delta =  Math.floor((now - time)/60)
                    var s = `${delta} 分钟前`
                    t.innerText = s
                }
            }, 1000)
        }

        var __main = function () {
            markContents()
            registerTimer()
            highlight()
        }

        __main()
</script>


{% endblock %}