models/topic.py
import time
from models import Model
from models.reply import Reply


class Topic(Model):
    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def __init__(self, form):
        self.id = None
        self.views = 0
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        # created time
        self.ct = int(time.time())
        # updated time
        self.ut = self.ct
        self.user_id = form.get('user_id', '')

    def user(self):
        from models.user import User
        u = User.find(self.user_id)
        return u

    def replies(self):
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,

)

from models.user import User
from models.topic import Topic
from models.reply import Reply
import os
import uuid
from utils import log

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""


@main.route("/")
def index():
    u = current_user()
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    # form = request.args
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        return redirect(url_for('topic.index'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


@main.route('/settings', methods=['GET', 'POST'])
def settings():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('settings.html', user=u)


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.find(id)
    if u is None:
        abort(404)
    else:
        ts = sorted(User.topics(u), key=lambda x:x.ct, reverse=True)
        rs = sorted(User.replies(u), key=lambda x:x.ct, reverse=True)
        rts = []
        for r in rs:
            rts.append(r.topic())
        return render_template('profile.html', user=u, topics=ts, reply_titles=rts)


def valid_suffix(suffix):
    valid_type = ['jpg', 'png', 'jpeg']
    return suffix in valid_type


@main.route('/image/add', methods=["POST"])
def add_img():
    u = current_user()

    # file 是一个上传的文件对象
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        # 上传的文件一定要用 secure_filename 函数过滤一下名字
        # ../../../../../../../root/.ssh/authorized_keys
        # filename = secure_filename(file.filename)
        # 2017/6/14/19/56/yiasduifhy289389f.png
        # import time
        # filename = str(time.time()) + filename
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        User.update(u.id, dict(
            user_image='/uploads/' + filename
        ))

    return redirect(url_for(".profile"))


# send_from_directory
# nginx 静态文件
@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory('user_image', filename)

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    print('DEBUG', form)
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic


main = Blueprint('topic', __name__)


@main.route("/")
def index():
    ms = Topic.all()
    u = current_user()
    return render_template("topic/index.html", ms=ms, u=u)


@main.route('/<int:id>')
def detail(id):
    # http://localhost:2000/topic/1
    m = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
def new():
    return render_template("topic/new.html")

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>

</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <a class='brand' href='/'>

          <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg" />

      </a>

      <form id='search_form' class='navbar-search' action="/search">
        <input type='text' id='q' name='q' class='search-query span3' value=''/>
      </form>
      <ul class='nav pull-right'>
        <li><a href='/'>首页</a></li>

        <li>
            <a href='/my/messages'>

              未读消息
            </a>
        </li>

        <li><a href='/getstart'>新手入门</a></li>
        <li><a href='/api'>API</a></li>

        <li><a href="/about" target="">关于</a></li>


        <li><a href='/setting'>设置</a></li>
        <li>
          <a href='/signout' data-method="post" rel="nofollow">退出</a>
        </li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>
{% block main %}{% endblock %}
</body>
</html>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}
帖子详情 {{ topic.title }}
{% endblock %}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title | test1}}
      	</span>
                <div class="changes">
            <span>
                发布于 2 天前
            </span>
                    <span>
                {% set u = topic.user() %}
                作者
                <a href="{{ url_for('index.user_detail', id=u.id) }}">
                    {{ u.username }}
                </a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a href="{{ url_for('index.user_detail', id=u.id) }}" class="user_avatar">
                    <img src="https://avatars2.githubusercontent.com/u/10721874?v=3&amp;s=120"
                         title="{{ u.username }}"/>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ u.username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 / {{ loop.length }}楼 •
                        <span class="gua-time" data-ct="{{ r.ct }}"></span>
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content|safe}}</div>
            </div>
        </div>
        {% endfor %}
        <div class='panel'>
    <div class='header'>
      <span class='col_fade'>添加回复</span>
    </div>
    <div class='inner reply'>
      <form id='reply_form' action='/5a9cf82f77dc4e0d2136ae0b/reply' method='post'>

        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='r_content' rows='8'></textarea>

            <div class='editor_buttons'>
              <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.." value="回复" >
            </div>
          </div>

        </div>

        <input type='hidden' name='_csrf' id="_csrf" value='tKu0OYAd-5aGVGWiBW09g_z1WYOZkv4vvzWI'/>
      </form>
    </div>
  </div>
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>
<script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            var code_list = es('pre code')
            for (var i = 0; i < code_list.length; i++) {
                var code = code_list[i]
                code.className = code.className.replace('lang', 'language')
            }
        }

        var registerTimer = function () {
            setInterval(function () {
                var times = es('.gua-time')
                for (var i = 0; i < times.length; i++) {
                    var t = times[i]
                    var time = Number(t.dataset.ct)
                    var now = Math.floor(new Date() / 1000)
                    var delta = now - time
                    var s = `${delta} 秒前`
                    t.innerText = s
                }
            }, 1000)
        }

        var __main = function () {
            markContents()
            registerTimer()
            highlight()
        }

        __main()

</script>

{% endblock %}

templates/topic/index.html
{% extends "topic/base.html" %}
{% block title %}
所有帖子
{% endblock %}
{% block main %}
    <div id="main">
        <div id='sidebar'>

      <div class='panel'>
        <div class="inner">
            <a href="/topic/new" class="create_topic_btn">
                <span class="span-success">发布话题</span>
            </a>
        </div>
      </div>
        <div class='panel'>
        <div class='header'>
          <span class='col_fade'>个人信息</span>
        </div>
        <div class='inner'>
          <div class='user_card'>
              <div>
                <a class='user_avatar' href="{{url_for('index.user_detail', id=u.id)}}">
                  <img src="https://avatars3.githubusercontent.com/u/3118295?v=4&amp;s=120">
                </a>
                <span class='user_name'><a class='dark'>{{u.username}}</a></span>

                <div class="space clearfix"></div>
                <span class="signature">
                    “
                        没有签名
                    ”
                </span>
              </div>
          </div>
        </div>
      </div>
    </div>



        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
{#                                <span>{{ t.replies() | count }} / {{ t.views }}</span>#}
                                <span>{{ t.reply_count() }} / {{ t.views }}</span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/topic/new.html
{% extends "topic/base.html" %}
{% block title %}
新建帖子
{% endblock %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}

templates/topic/topic.html
{% extends "topic/base.html" %}
{% block title %}
帖子详情 {{ topic.title }}
{% endblock %}
{% block main %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}